### ISSUE TITLE
Building a CO-OP map in Portal 1 Style causes "Failure to compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#1289]
```
VBSP failed.

[INFO] vbsp.main(): BEE VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Setting Coop Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: COOP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (18 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in <BEE2_PORTAL_1>/items/coop_spawn:
Traceback (most recent call last):
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 463, in check_all
    for name in aliases:
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 353, in test
    for res in results[:]:
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 340, in test_result
    name=res.real_name,
ValueError: "ATLAS_SpawnPoint" is not a valid condition result!
```

**Comment by ZombiePwner1** [comment]
It's to do with atlas's spawn point.

**Comment by Luke18033** [comment]
@ZombiePwner1 The same issue probably applies with P-Body's spawn, but it's quitting the compiler before it even gets to that point.

**Comment by TeamSpen210** [comment]
This is part of the Tag support I added, you'll need to rebuild the compiler for it to work.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Okay, ill ask you help on recompiling it when i log in Steam then.
