### ISSUE TITLE
1970s Cube Droppers cause compile failure

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1301]
```
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'APERTURE_TAG_NIGEL'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 4
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 3
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (459 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[WARNING] cond.core.res_make_tag_fizzler(): Toggle: it324756
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\connections.py", line 235, in res_linked_cube_dropper
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 463, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 342, in test_result
  File "F:\Git\BEE2.4\src\conditions\connections.py", line 238, in res_linked_cube_dropper
Exception: Unknown cube "linkage" value (3) in dropper!
```

**Comment by Luke18033** [comment]
Oh, I figured it out. It's the linking droppers, they're all set to 3.
