### ISSUE TITLE
Excursion Funnels cause compile failure

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#1324]
```
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 463, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 340, in test_result
ValueError: "FunnelLight" is not a valid condition result!
```

**Comment by TeamSpen210** [comment]
I made funnels produce light, which works fine but not with older compilers.
