### ISSUE TITLE
Can make double angled panel and double panel brigde ?

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2-items#1589]
Double Panel: 
Has The Same Functions And Animation but Has the size of two blocks.

Double Panel Brigde:
Has The same functions of the panel brigde but have 3 (Or 4 to round up) and have the textures of the angled panel,(the textures of the panel brigde is Gray and dark gray squares(It's not beautiful))

**Comment by Luke18033** [comment]
- Double angled panel: Sure.
- Double panel bridge: Send a screenshot, I have no idea what you're trying to say.
- Half panel: A static version is already implemented, and I've requested a non-static version (#1456).

**Comment by XdplayerdX** [comment]
http://imgur.com/a/2j0Ub

**Comment by TheDarkBomber** [comment]
Please send images using the markdown system, so people don't actually have to click the links.

**Comment by XdplayerdX** [comment]
http://i.imgur.com/HKhOMQ3.jpg?1

![](http://i.imgur.com/g7Lb22I.jpg)

**Comment by XdplayerdX** [comment]
Sorry

**Comment by Luke18033** [comment]
Currently we can't change the panel color of the Drawbridge in the editor. I don't know why the map is going fullbright, there must be a leak somewhere. Why is the reflection gel dropper blue?

**Comment by XdplayerdX** [comment]
This is the image of the SCINCE TEST
![](https://camo.githubusercontent.com/cca721b024e8c45f11dc4a68f750b881791aceb3/687474703a2f2f692e696d6775722e636f6d2f484b684f4d51332e6a70673f31)
But i'm compiled AND THIS TEST AS APEARED
![](https://camo.githubusercontent.com/9d1cd4663aab97115792ef85d05ff8792be6d46e/687474703a2f2f692e696d6775722e636f6d2f67374c623232492e6a7067)
Have any idea wath is that ?
The purple gel dont make anything and i'm get a only yeallow portal portal gun
and if I try edit the I get one compile error,
Wath is this test chamber ?

**Comment by TeamSpen210** [comment]
I know what that is - it's a dev map accidentally included in the BEE2.2 download, which should be overwritten by your maps. What version did you install?

**Comment by Endermage77** [comment]
The panel bridge is already implemented;
We call it the Drawbridge.
It closes upward instead of downward, though.

**Comment by XdplayerdX** [comment]
i have initially te last release of the bee 2 (2.4)
but i tryed install the alpha version for try use the living panel 
and I can't use that and that give-me a compile error
I tryed Check the integrity of the files and reinstall the files damaged by bee 2 alpha
and tryed re-use bee 2.4 and I tryed explain yours questions and I get that when I try compile
![](https://camo.githubusercontent.com/9d1cd4663aab97115792ef85d05ff8792be6d46e/687474703a2f2f692e696d6775722e636f6d2f67374c623232492e6a7067)

**Comment by XdplayerdX** [comment]
I can't compile my chambers now |:(
![20170215215220_1](https://cloud.githubusercontent.com/assets/25773302/23000805/49fe5e18-f3c9-11e6-84a4-703e08a15c42.jpg)

**Comment by Luke18033** [comment]
@XdplayerdX Log?

**Comment by XdplayerdX** [comment]
I'm making again a Check the integrity of the files to retire all the bee 2 mod again

**Comment by XdplayerdX** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/25773302/23001227/4c6d9a36-f3cb-11e6-9513-c389740770a6.png)

**Comment by XdplayerdX** [comment]
![20170215221919_1](https://cloud.githubusercontent.com/assets/25773302/23001609/f5262eda-f3cc-11e6-9c0e-529ee8fb71bc.jpg)

The LOG
NET_GetBindAddresses found 192.168.0.100: 'Realtek PCI GBE Family Controller'
Opened Steam Socket NS_SERVER ( socket 1496 )
Opened Steam Socket NS_CLIENT ( socket 1492 )
Network: IP 192.168.0.100, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Failed to init 'maps/soundcache/_master_brazilian.cache'
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
Host_WriteConfiguration: Wrote cfg/config.cfg
Didn't find Active Steam Controller to Load Menu Controls
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
[PORTAL2 PUZZLEMAKER]  New chamber!
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.100, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 1504 )
Opened Steam Socket NS_CLIENT ( socket 1492 )
Network: IP 192.168.0.100, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/door_frame.vmt
patch, (*insert*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/crusher_back.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_cube_dropper.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_cube_dropper.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_angled_white_90.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_angled_white_90.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_angled_white_45.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_angled_white_45.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_angled_black_90.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_angled_black_90.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_angled_black_45.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_angled_black_45.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_angled_ghost_90.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_angled_ghost_90.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_angled_ghost_45.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_angled_ghost_45.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_pist_grate.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_pist_grate.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_pist_1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_pist_1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_pist_2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_pist_2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_pist_3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_pist_3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_pist_top.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_pist_top.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_p1_pist_4.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_p1_pist_4.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_ditch.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_faithplate_128.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_faithplate_128.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_a.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_b.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/floor_panels.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Connection to Steam servers successful.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198295269118\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 64 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198295269118\autosave.p2c

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'fizz_visiblity': '0', 'bottomless_pit': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Exit (1)
[INFO] vbsp.mod_entryexit(): Using random SP Entry (7)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in <BEE2_PORTAL_1>/items/exit_door:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 463, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 342, in test_result
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1580, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 353, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 342, in test_result
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1580, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 348, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 517, in check_flag
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1472, in debug_flag
  File "F:\Git\srctools\srctools\vmf.py", line 1725, in __str__
TypeError: Can't convert 'int' object to str implicitly

**Comment by XdplayerdX** [comment]
the steam can't unistall the bee mod |:(

**Comment by quat1024** [comment]
You can get rid of the changes BEE2 does to your Portal 2 game by verifying the game cache:

![](https://puu.sh/u6hap.png)

![](https://puu.sh/u6hd2.png)

**Comment by TeamSpen210** [comment]
That doesn't do it properly. In the apo, go and remove it from the game in the menu bar, which uninstalls all traces.

**Comment by XdplayerdX** [comment]
I'm searched in the main portal 2 pasts for Bee and deleted everything,and i'm follow that steps
https://camo.githubusercontent.com/977541198d0b8199c59768fffa3a67fa5d562f1b/68747470733a2f2f7075752e73682f75366864322e706e67
and the game as fully restored
