### ISSUE TITLE
General Error "No Indexing Without Children"

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2-items#1604]
Hey ho, more errors! And a different naming convention, too.
This one happens when I compile no matter what.
If it helps, I use the Dev version when this happens, tried reinstalling BEE2 and Portal 2.

Log:
```
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.100, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2372 )
Opened Steam Socket NS_CLIENT ( socket 2376 )
Network: IP 192.168.1.100, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_orange.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Requested non-existent write path LOCAL!
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 32 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "d:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'voice_pack': 'BEE2_WHEATLEY', 'use_screenshot': '1'}
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3535, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 361, in load_settings
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 495, in add
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 310, in parse
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 256, in __init__
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 318, in setup
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 328, in setup_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1742, in make_static_pist_setup
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1738, in <dictcomp>
  File "F:\Git\srctools\srctools\property_parser.py", line 702, in __getitem__
IndexError: Can't index a Property without children!
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3535, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 361, in load_settings
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 495, in add
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 310, in parse
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 256, in __init__
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 318, in setup
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 328, in setup_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1742, in make_static_pist_setup
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1738, in <dictcomp>
  File "F:\Git\srctools\srctools\property_parser.py", line 702, in __getitem__
IndexError: Can't index a Property without children!

```

**Comment by TeamSpen210** [comment]
Reninstalling won't help, this is because the dev version uses some features not in the released compiler.

**Comment by Luke18033** [comment]
You need the BEE2.4 application dev version.

**Comment by TheDarkBomber** [comment]
Disable the Rexaura Package.
