### ISSUE TITLE
BEE2.4 Problem

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2-items#1661]
For some odd reason, when I export my items to Portal 2, I get this error:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 844, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 607, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 389, in refresh_cache
  File "F:\Git\BEE2.4\src\utils.py", line 544, in merge_tree
shutil.Error: [('../cache/resources/instances\\50s\\items\\bee\\drawbridge', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\drawbridge', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee\\\\drawbridge'"), ('../cache/resources/instances\\50s\\items\\bee\\hep', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\hep', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee\\\\hep'"), ('../cache/resources/instances\\50s\\items\\bee\\vent', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\vent', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee\\\\vent'")]

I posted this on Steam, but it was a longer error. TeamSpen210 responded, saying: "This error implies you for some reason have security restrictions on some folders in your Portal 2 Folder."
I went through most folders (I skipped the ones that weren't in my language) and removed restrictions with security. However, I still got an error. Is there a fix for this?

BTW, The items still export, I was just wondering if this could be fixed.

This here is an image of what items I was using:
![n oh](https://cloud.githubusercontent.com/assets/25728252/23580220/5be1ec1c-00cb-11e7-9a24-b1482896f84e.PNG)

**Comment by Luke18033** [comment]
It's still an access error, specifically to the `sdk_content` folder, or something in it. Check the permissions there.

**Comment by hop193** [comment]
Well, I tried doing that, and now I have a permanent error. The error:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 146, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 1928, in init_windows
  File "F:\Git\BEE2.4\src\UI.py", line 761, in refresh_pal_ui
IndexError: list index out of range

**Comment by TeamSpen210** [comment]
This means it tried to select a palette after the ones in the list. Either palette files are missing, or it's a corrupt config file. Open `config/config.cfg`, and in the `[Last_Selected]` section set `palette` to `0`.

**Comment by hop193** [comment]
New error:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 844, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 607, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 389, in refresh_cache
  File "F:\Git\BEE2.4\src\utils.py", line 544, in merge_tree
shutil.Error: [('../cache/resources/instances\\50s\\items\\barrier', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\barrier', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\barrier'"), ('../cache/resources/instances\\50s\\items\\bee\\drawbridge', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\drawbridge', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee\\\\drawbridge'"), ('../cache/resources/instances\\50s\\items\\bee\\hep', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\hep', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee\\\\hep'"), ('../cache/resources/instances\\50s\\items\\bee\\vent', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\vent', "[WinError 5] Access is denied: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee\\\\vent'")]

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
