### ISSUE TITLE
Instant Crash?

### ISSUE THREAD

**Issue by 1nsider-rblx** [BEEmod/BEE2-items#1924]
Okay, I have tried a different "package", and tried lots of other things, I have a error that just can't fix!
Booting up my BEE2 just results with this error (exact):

---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 79, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 985, in load
AttributeError: 'SplashScreen' object has no attribute 'withdraw'

This has been copied to the clipboard.
---------------------------
OK   
---------------------------

Any way to stop it, for real?

**Comment by ZombiePwner1** [comment]
@Arynn24 Nope only way is to replace the prl 25 configs with prl 24.

**Comment by Arynn24** [comment]
@ZombiePwner1 It doesn't work. Any other way?

**Comment by ZombiePwner1** [comment]
@Arynn24 I mean that u need to grab the config files from prl 24 and put them in the prl 25 configs.

**Comment by Arynn24** [comment]
@ZombiePwner1 How? plr 24 doesn't have a config file... At least, that's what I saw

**Comment by ZombiePwner1** [comment]
@Arynn24 It does go into your prl 24 files where the packages and stuff is located and look for a file name config.

**Comment by Arynn24** [comment]
@ZombiePwner1 Exactly where and what I can't find.

**Comment by Arynn24** [comment]
So, is there any different way? Something like reinstalling, rebooting, or etc?

**Comment by Arynn24** [comment]
So, I found out, its the package! I installed prl 24 with package 25, and It gives a crash, I tried it with package 24 and it worked. So the package is our issue.

**Comment by Luke18033** [comment]
This would be an app issue, probably fixed now anyway.
