### ISSUE TITLE
Resizable Triggers causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2161]
VBSP failed.

[INFO] vbsp.main(): BEE VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 5 cube types, 1 dropper types and 1 addons.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (1288 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[WARNING] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'2', '1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'72', '78'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'24'}
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in <BEEMOD_1>/items/trigger:
Traceback (most recent call last):
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 483, in check_all
    condition.test(inst)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 304, in test
    should_del = self.test_result(inst, res)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 293, in test_result
    return func(VMF, inst, res)
  File "<string>", line 1, in <lambda>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\resizableTrigger.py", line 110, in res_resizeable_trigger
    ent.remove()
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\srctools\srctools\vmf.py", line 1732, in remove
    self.map.remove_ent(self)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\srctools\srctools\vmf.py", line 317, in remove_ent
    self.entities.remove(item)
ValueError: list.remove(x): x not in list

**Comment by LautaroL20** [comment]
It seems that ill have to use an OR Gate for now....
