### ISSUE TITLE
Connection Signage causes "Failure To Compile" 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#2162]
[ERROR] cond.core.check_all(): Error in <Item ITEM_BEE2_SIGNAGE_ANTLINE all_conf>:
Traceback (most recent call last):
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 483, in check_all
    condition.test(inst)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 304, in test
    should_del = self.test_result(inst, res)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 293, in test_result
    return func(VMF, inst, res)
  File "<string>", line 1, in <lambda>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 1207, in res_sub_condition
    res.value.test(base_inst)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 304, in test
    should_del = self.test_result(inst, res)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\__init__.py", line 293, in test_result
    return func(VMF, inst, res)
  File "<string>", line 1, in <lambda>
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\conditions\entities.py", line 98, in res_insert_overlay
    force_type=TEMP_TYPES.detail,
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\template_brush.py", line 466, in import_template
    template = get_template(temp_name)
  File "C:\Users\Lautaro\Documents\BEEMOD 2.4 GHITUB\BEE2.4\src\template_brush.py", line 424, in get_template
    raise InvalidTemplateName(temp_name) from None
template_brush.InvalidTemplateName: Template not found: "bee2_signage_clean_sign2_floor"
Valid templates:

**Comment by TeamSpen210** [comment]
I merged the templates into one, and forgot to fix up the IDs in that.

**Comment by LautaroL20** [comment]
Could you fix this? I need to use the signage item for something.

**Comment by TeamSpen210** [comment]
This is fixed.
