### ISSUE TITLE
Paint Gun Activation Field not working

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2-items#2418]
Everytime I connect a Paint Gun Activation Field item to a fizzler and try to build the puzzle I get this error in the console.

```
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Aperture Tag/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_60s'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 12 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Entry (2)
[INFO] vbsp.mod_entryexit(): Using random SP Exit (4)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (172 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[ERROR] cond.core.check_all(): Error in <APERTURE_TAG_ITEMS>/items/gel_fizz_50s:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 483, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "F:\Git\BEE2.4\src\conditions\apTag.py", line 206, in res_make_tag_fizzler
KeyError: 'TAG_GEL_GUN'
```

What happens is in this video.

http://www.mediafire.com/file/hggz33o5mdtfmx7/Error.avi

**Comment by TeamSpen210** [comment]
Apparently 50s style doesn't have a Tg Fizzler item defined, or otherwise I messed it up. Do you have the right package/compiler combo?

**Comment by Fazbear189** [comment]
I am using the 60s style. Not the 50s. I will check If I have it.

**Comment by TeamSpen210** [comment]
Apparently I didn't update this item at all for 50s style.
