### ISSUE TITLE
Signage items causes a compile error in Portal 1 Style

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#2512]
[ERROR] cond.core.check_all(): **Error in <BEE2_SIGNAGE>/items/sign_p1**:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 485, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1217, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\entities.py", line 98, in res_insert_overlay
  File "F:\Git\BEE2.4\src\template_brush.py", line 467, in import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 425, in get_template
template_brush.InvalidTemplateName: **Template not found: "bee2_signage_clean_sign2_floor"**

_Copied from original issue: BEEmod/BEE2.4#844_

**Comment by Firepal** [comment]
I didn't know item bugs were supposed to be here. Thanks anyway !

**Comment by TeamSpen210** [comment]
Fixed by no longer existing.
