### ISSUE TITLE
Signage in P1 Style does a compile error

### ISSUE THREAD

**Issue by Firepal** [BEEmod/BEE2-items#2723]
Here's what the console spits out then:
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (117 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.monitor.mon_remove_bullseyes(): Bullseye defaultdict(<class 'int'>, {Vec_tuple(x=320.0, y=832.0, z=0.0): 1})
[INFO] cond.monitor.mon_remove_bullseyes(): Pos: Vec_tuple(x=320.0, y=832.0, z=0.0) -> 
[WARNING] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[WARNING] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[INFO] brushes.res_import_template(): IDS: {'1', '2'}
[INFO] brushes.res_import_template(): IDS: {'1', '2'}
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
**[ERROR] cond.core.check_all(): Error in <BEE2_SIGNAGE>/items/sign_p1:**
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 488, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 307, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 296, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1267, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 307, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 296, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1267, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 307, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 296, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\entities.py", line 98, in res_insert_overlay
  File "F:\Git\BEE2.4\src\template_brush.py", line 467, in import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 425, in get_template
template_brush.InvalidTemplateName: Template not found: "bee2_signage_clean_arrow

Then it shows valid templates. Volvo, please foxo.

**Comment by Firepal** [comment]
oh crap. Didn't know this still wasn't fixed. woopsie.
