### ISSUE TITLE
Missing models and textures in editor and ingame

### ISSUE THREAD

**Issue by Wh4tsMyName** [BEEmod/BEE2-items#2894]
When loading up the Portal 2 level editor, several textures and models are missing both in the editor itself and ingame. For example, in the editor, many of the palette textures are the pink-and-black checkerboards and the models shown when placing them are blue ERRORs. Not only this, but ingame, some models don't exist or are ERRORs, some unportalable surfaces are portalable and glowing white, and the large observation room doesn't turn on.

[Here's some pictures I took showing the problems.](https://imgur.com/gallery/3YpwnQ0) I'm using BEE2 4.33.1 and version 4.33.0 packages.

**Comment by TeamSpen210** [comment]
Sounds like the resources aren't being copied over. Quit Portal 2 and Hammer if they're open, then go to File > Options > Development and make sure "Preserve Game Directory" is unchecked. Then go back to General and press "Reset Package Cache, wait for the app to restart and then export again.

**Comment by Wh4tsMyName** [comment]
Preserve Game Directory was already unchecked, but when trying the Reset Package Cache option, this error pops up. Just as a note, there is no "Spencer Brown" user on my computer and there is no F:\ drive. I also had to manually retype the error, if that's important.

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, _load_backward_compatible
  File "F:\Git\BEE2.4\src\tk_tools.py", line 33, in <module>
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1863, in wm_iconbitmap
_tkinter.TclError: bitmap "../BEE2.ico" not defined
```

**Comment by LautaroL20** [comment]
Try following the 7 steps contained in the following link, see if it fixes your problem: https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

**Comment by Wh4tsMyName** [comment]
That worked for me. Thanks for the help!
