### ISSUE TITLE
help?!

### ISSUE THREAD

**Issue by adadadbaba** [BEEmod/BEE2-items#2959]
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 119, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1075, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 368, in parse
srctools.property_parser.KeyValError: Block opening ("{") required, but hit EOF!
A "name" line was located at the end of the file, which needs a {} block to follow.
Error occurred with file "appmanifest_620.acf".

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to the user interface must be posted here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the items, only.
