### ISSUE TITLE
Catastrophic failure when trying to select where the game is executed

### ISSUE THREAD

**Issue by Kingmiami** [BEEmod/BEE2-items#2961]
It states 

![failure](https://user-images.githubusercontent.com/49174731/55368404-b98ca600-54bf-11e9-9027-fbd60e14ec7a.PNG)

I did the steps correctly, why is this happening?

(btw, i have custom music installed)

**Comment by TeamSpen210** [comment]
Where did you install it to?

**Comment by TeamSpen210** [comment]
Also, which version of Windows are you using?

**Comment by Kingmiami** [comment]
> Where did you install it to?
Portal or BEE2? I installed the newest version of bee2 and added the packages file. I installed bee2 @ downloads

**Comment by Kingmiami** [comment]
Also, using newest version of windows

**Comment by TeamSpen210** [comment]
Post a copy of `BEE2/logs/bee2.log` please.

**Comment by Kingmiami** [comment]
@TeamSpen210 [BEE2.log](https://github.com/BEEmod/BEE2-items/files/3031925/BEE2.log)

**Comment by Kingmiami** [comment]
If all else fails, i'll reinstall

**Comment by xDadiKx** [comment]
@TeamSpen210 That image is from this [Reddit Post](https://www.reddit.com/r/Portal/comments/8u3y81/i_tried_running_portal_shortcut_in_paintnet_and/)
I think that this issue is supposed to be an April fools joke.

**Comment by Kingmiami** [comment]
@TeamSpen210 
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 82, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1343, in load
  File "F:\Git\BEE2.4\src\UI.py", line 445, in quit_application
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 64, in write_settings
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 33, in get_curr_settings
  File "F:\Git\BEE2.4\src\UI.py", line 475, in save_load_selector_win
NameError: name 'style_win' is not defined

Help i reninstalled still broken

**Comment by TeamSpen210** [comment]
What happened before that dialog? Where is your Portal 2 exe that you chose? Try going to `%APPDATA%/BEEMOD2/`, and delete the config files there.

**Comment by Kingmiami** [comment]
@TeamSpen210 What happened before was the same thing that happened here. It said "Portal 2 Catastrophic Failure" 

Deleted config files, got the catastrophic failure again

**Comment by Kingmiami** [comment]
tried using an older version
![ffs2](https://user-images.githubusercontent.com/49174731/55555429-4481c200-56b3-11e9-8b1c-0eec218a1184.PNG)
ffs

is this something with the game and not beemod?

**Comment by Luke18033** [comment]
Not sure what was happening here
