### ISSUE TITLE
VBSP failing no matter what I do. [Compile Error]

### ISSUE THREAD

**Issue by Master-64** [BEEmod/BEE2-items#3000]
So here's my situation. For the past few months, I have never been able to compile a map with VBSP. It doesn't matter if I get the latest version, or re-install literally every file, or reset my config, nothing. I am baffled that it still doesn't work. Anyone know what in the world is going on?

Logs when compiling:

VBSP failed.

[I] vbsp.main(): BEE2 4.34.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "G:/Steam2/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "G:/Steam2/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'voice_pack': 'BEE2_GLADOS_P1'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 3
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (34 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[E] cond.core.check_all(): Error in <BEEMOD_1>/items/trigger:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 514, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 322, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 311, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\resizableTrigger.py", line 125, in res_resizeable_trigger
KeyError: 'tr24'

This is my compile when I compiled a test map on the clean theme with no corridor changes.

**Comment by Master-64** [comment]
Forgot to mention this, but I'm running the latest version of Beemod as of June 2, 2019.

**Comment by Master-64** [comment]
(fixed this, was caused by putting a single trigger inside a portal gun spawner)
