### ISSUE TITLE
Build Error W/ Old Aperture [50s] Unst. Scaffolds & Screens

### ISSUE THREAD

**Issue by HelloIamapersonthatisalive** [BEEmod/BEE2-items#3025]
Scaffold Error: 
-Running launcher 4.35.1
-Running packages 4.35.0
-2 wall emitters pointing at each other, connected
-50s Theme

[Console Excerpt Of Scaffold Gen]

[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[E] cond.core.check_all(): Error in <BEE2_UNST_SCAFFOLD>/items/pist_50s:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 514, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 322, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 311, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\scaffold.py", line 154, in res_unst_scaffold
  File "F:\Git\BEE2.4\src\item_chain.py", line 71, in chain
  File "F:\Git\BEE2.4\src\connections.py", line 593, in delete_antlines
  File "F:\Git\srctools\srctools\vmf.py", line 1792, in remove
  File "F:\Git\srctools\srctools\vmf.py", line 302, in remove_ent
ValueError: list.remove(x): x not in list

Screen Error:
-Running launcher 4.35.1
-Running packages 4.35.0
-Screen on wall, no connections
-50s Theme
-Looks like missing instance

[Console Excerpt]

[I] <valve>.vbsp(): Could not open instance file instances/BEE2/50s/items/screen/monitor.vmf

**Comment by Luke18033** [comment]
Missing monitor instances should be fixed now, not sure about scaffolds?

**Comment by Konclan** [comment]
You're using 4.35, please only open issues about the latest version
