### ISSUE TITLE
Unstationary Scaffold Piston Emitter Causes Build Error When Placed On Floor

### ISSUE THREAD

**Issue by Libbybapa** [BEEmod/BEE2-items#3206]
Title says it all.

**Comment by Libbybapa** [comment]
Well, maybe the title didn't say quite all.  Here's a bit more:

`[E] cond.core.check_all(): Error in <BEE2_UNST_SCAFFOLD>/items/pist_clean:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 514, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 322, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 311, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\scaffold.py", line 199, in res_unst_scaffold
  File "F:\Git\BEE2.4\src\conditions\scaffold.py", line 46, in get_config
AttributeError: 'NoneType' object has no attribute 'inst'
`
