### ISSUE TITLE
"ITEM_TSPEN_LARGE_CATAPULT" being defined twice causes BEE2 to crash

### ISSUE THREAD

**Issue by kinker31** [BEEmod/BEE2-items#3305]
### The Error Itself:
```
[INFO] packageLoader.load_packages(): Reading objects from "TSPEN_LARGE_FAITH"...
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 92, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 473, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 602, in parse_package
Exception: ERROR! "ITEM_TSPEN_LARGE_CATAPULT" defined twice!
```
### System Specs:

- Windows 10 (Most Recent Update)
- AMD Radeon G7 Series
- Most recent BEE2 version

**Comment by Flash4433** [comment]
You updated BEE2 Packages on top of the older ones, right? You shouldn't do that: just delete all of the default ones and put the new ones. Should fix that.

**Comment by Luke18033** [comment]
This would indeed be caused by that, TeamSpen renamed that package so you'd have two copies of it.
