### ISSUE TITLE
Geometry: Signage does not appear

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3363]
I'm not sure if this is actually specific to Overgrown, but...
![image](https://user-images.githubusercontent.com/19228201/86871374-03831500-c08f-11ea-9a1b-6160c49c2a07.png)
![image](https://user-images.githubusercontent.com/19228201/86871350-f6662600-c08e-11ea-8f05-f047a5c1398f.png)
This variant has been updated according to the tiling system checklist, so I'm not sure exactly what's going on here.

**Comment by Luke18033** [comment]
Doesn't appear to be style-specific

**Comment by Luke18033** [comment]
Hammer view. The instance containing the `func_noportal_volume` is present, but the actual overlays are nowhere to be found. There's also a random `info_particle_system` floating in front of it, for some reason? It doesn't have any  keyvalues set, but one is located above every signage in the map.
![image](https://user-images.githubusercontent.com/19228201/87186442-5e3f8b00-c2a0-11ea-912f-d74367953f44.png)

**Comment by TeamSpen210** [comment]
When debugging, I often just have it spawn one of those in so I can see the position and direction it's trying to check. Seems I forgot to remove that...

**Comment by TeamSpen210** [comment]
Ah, check the log, it'll have an error mentioning the surface can't be found.

**Comment by Luke18033** [comment]
This looks important.
```
[WARNING] cond.signage.res_signage(): Can't place signage at (2800 448 1088) in (-0 -0 1) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (2240 448 624) in (-1 0 -0) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (2112 1344 656) in (-1 0 -0) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (2112 1856 656) in (-1 0 -0) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (576 1344 656) in (1 0 -0) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (400 2496 576) in (0 0 -1) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (320 2752 1136) in (1 -0 -0) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
[WARNING] cond.signage.res_signage(): Can't place signage at (576 1856 656) in (1 0 -0) direction!
Traceback (most recent call last):
  File "conditions\signage.py", line 181, in res_signage
  File "tiling.py", line 1393, in find_tile
KeyError: 'Badly offset into a tile!'
```
