### ISSUE TITLE
BumbleBall will cause "Failure To Compile" when the choosen number on its contex menu is above 3

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3404]
I did not test other styles than Clean for now, but i bet this would also affect the others as well. Console log:

`````
VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.mod_entryexit(): Setting SP Entry to 5
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (17 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[E] cond.core.check_all(): Error in MetaCondition "link_cubes":
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 537, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 325, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 314, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\cubes.py", line 1139, in link_cubes
ValueError: Unknown cube "linkage" value (4) in cube!
A cube has a timer set which doesn't match any droppers.````

**Comment by LautaroL20** [comment]
This also affects the Bomb Cube the exact same way as BumbleBall and since that the issue seems to be related wich eachother ill going to reuse this same issue. Console log is exactly the same as the BumbleBall´s one.

**Comment by Luke18033** [comment]
That error would indicate that you haven't placed any droppers with a matching timer value.

**Comment by LautaroL20** [comment]
Well, none of both items description says anything like "place a dropper with a matching timer value", so at this point, i am not sure if this is intentinal or not...

**Comment by Luke18033** [comment]
It's a feature of all cube items, setting it to the same timer value as a dropper will link the cube to that dropper, triggering an auto-respawn when fizzled. But if there's no dropper with the same timer value, it should just ignore it instead of failing the compile.
