### ISSUE TITLE
Sendificator Slim causes "Failure To Compile"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#3408]
Complete console log obtained after writte "Developer 2":

`````
VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (2 antlines)
[I] vbsp.mod_entryexit(): Setting SP Entry to 5
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (26 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.sendtor.res_sendificator(): Relay: <Entity>: 
 | {
 | 	 targetname = "@sendtor174_las_relay_1"
 | 	 origin = "8 832 448"
 | 	 angles = "-0 0 0"
 | 	 classname = "logic_relay"
 | 	 StartDisabled = "0"
 | 	<Output> OnTrigger -> !self -> RunScriptCode (::sendtor_source <- self;)
 | 	<Output> OnTrigger -> @sendtor_fire -> Trigger
 | }
 | 
 |___

[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[W] packing.pack_list(): Packlist "PACK_HMW_SENDTOR_LOGIC" does not exist!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] vbsp.add_screenshot_logic(): Added Screenshot Logic
[I] cond.core.check_all(): Map has attributes: ['goo', 'laseremitter', 'laser', 'deadly', 'sendificator', 'sendtor', 'pedestalbutton', 'needsportalman', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=5226, misses=345, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/bee2/logic/hmw/sendtor_manager.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/Steam/steamapps/common/Portal 2/portal2/', 'D:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 16 threads
[I] <valve>.vbsp(): materialPath: D:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): fixing up env_cubemap materials on brush sides...
[I] <valve>.vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] <valve>.vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] <valve>.vbsp(): Processing areas...done (0)
[I] <valve>.vbsp(): Building Faces...done (0)
[I] <valve>.vbsp(): Chop Details...done (0)
[I] <valve>.vbsp(): Find Visible Detail Sides...
[I] <valve>.vbsp(): Merged 392 detail faces...done (0)
[I] <valve>.vbsp(): Merging details...done (0)
[I] <valve>.vbsp(): FixTjuncs...
[I] <valve>.vbsp(): PruneNodes...
[I] <valve>.vbsp(): WriteBSP...
[I] <valve>.vbsp(): done (0)
[I] <valve>.vbsp(): writing D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
[I] <valve>.vbsp(): done (0)
[I] <valve>.vbsp(): Finding displacement neighbors...
[I] <valve>.vbsp(): Finding lightmap sample positions...
[I] <valve>.vbsp(): Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
[I] <valve>.vbsp(): Building Physics collision data...
[I] <valve>.vbsp(): done (2) (407530 bytes)
[I] <valve>.vbsp(): Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
[I] <valve>.vbsp(): Water found with no water_lod_control entity, creating a default one.
[I] <valve>.vbsp(): Compacting texture/material tables...
[I] <valve>.vbsp(): Reduced 2967 texinfos to 518
[I] <valve>.vbsp(): Reduced 60 texdatas to 54 (1816 bytes to 1622)
[I] <valve>.vbsp(): Writing D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): nummapplanes:     (  8376 / 65536 )
[I] <valve>.vbsp(): nummapbrushes:    (  1112 /  8192 )
[I] <valve>.vbsp(): nummapbrushsides: (  8960 / 65536 )
[I] <valve>.vbsp(): num_map_overlays: (    12 /   512 )
[I] <valve>.vbsp(): nummodels:        (    36 /  1024 )
[I] <valve>.vbsp(): num_entities:     (   395 / 16384 )
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): 2 seconds elapsed
[I] <valve>.vbsp(): CDynamicFunction: Loading library 'Kernel32.dll' (77080000)
[I] <valve>.vbsp(): CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 776D25D0
[I] <valve>.vbsp(): CDynamicFunction: Closing library 'Kernel32.dll' (77080000)
[I] vbsp.run_vbsp(): VBSP Done!
[I] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('1112', '8192'), 'overlay': ('12', '512'), 'entity': ('395', '16384')}
[I] BEE2_config.save(): Saving changes in config "C:\Users\Lautaro\AppData\Roaming\BEEMOD2\config\compile.cfg"!
[I] vbsp.make_vrad_config(): Generating VRAD config...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2101, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 1754, in make_vrad_config
  File "F:\Git\BEE2.4\src\cubes.py", line 637, in write_vscripts
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/inject/cube_vscript_01.nut'
[4504596] Failed to execute script compiler_launch
`````

**Comment by Luke18033** [comment]
You realize `developer` mode doesn't make any difference with compile errors, right? The log is always shown and doesn't contain any less information or anything.

**Comment by LautaroL20** [comment]
> You realize `developer` mode doesn't make any difference with compile errors, right? The log is always shown and doesn't contain any less information or anything.

Why then Spencer usually recommends using `developer 2` when someone is having compiling errors then?

**Comment by Luke18033** [comment]
He doesn't? Developer mode forces compile logs to be shown in the console, but if the compile fails that happens anyway. The only case where developer mode would be necessary is if the compile succeeded but you still needed the log, which is pretty rare. And even then you only need `developer 1`, 2 just causes I/O events and a few other things to be shown.

**Comment by LautaroL20** [comment]
The commit that fix this, seems to be: https://github.com/BEEmod/BEE2.4/commit/1ceb125f00b345613211632800c40e1b20c49030, and i was wonder if that commit would also solve the problem with the main Sendificator? (issue: #3307).

**Comment by TeamSpen210** [comment]
Yep, it's the same issue.
