### ISSUE TITLE
bug with bee2 AGAIN

### ISSUE THREAD

**Issue by lucasfelez** [BEEmod/BEE2-items#3579]
a moment it dont ever work the  loading work good,but when i play (texture are good but when i finished the level) it put me an error the preserves game directories option has been unchecked.

**Comment by lucasfelez** [comment]
oh and i have the error 1:Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\contextWin.py", line 399, in adjust_position
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1053, in winfo_rootx
_tkinter.TclError: bad window path name ".!frame3.!frame.!palitem55"
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
  File "F:\Git\BEE2.4\src\contextWin.py", line 399, in adjust_position
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1053, in winfo_rootx
_tkinter.TclError: bad window path name ".!frame3.!frame.!palitem55"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\contextWin.py", line 399, in adjust_position
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1053, in winfo_rootx
_tkinter.TclError: bad window path name ".!frame3.!frame.!palitem55"
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
  File "F:\Git\BEE2.4\src\contextWin.py", line 399, in adjust_position
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1053, in winfo_rootx
_tkinter.TclError: bad window path name ".!frame3.!frame.!palitem55"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
  File "F:\Git\BEE2.4\src\contextWin.py", line 399, in adjust_position
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1053, in winfo_rootx
_tkinter.TclError: bad window path name ".!frame3.!frame.!palitem55"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\contextWin.py", line 399, in adjust_position
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1053, in winfo_rootx
_tkinter.TclError: bad window path name ".!frame3.!frame.!palitem55"

**Comment by Thedoczek** [comment]
Maybe you unchecked but didn't export again?

**Comment by lucasfelez** [comment]
> Maybe you unchecked but didn't export again?

i restarted many MANY MANY times so yeah

**Comment by FrozenDragon0** [comment]
@lucasfelez Have you fixed the issue?

**Comment by lucasfelez** [comment]
> @lucasfelez Have you fixed the issue?

sorry for the bigggggest late but no still nnot working

**Comment by Luke18033** [comment]
Not really sure what's going on here, let us know if you still have this issue.
