### ISSUE TITLE
Compile error for unknown reason

### ISSUE THREAD

**Issue by zooz8882** [BEEmod/BEE2-items#3838]
I was using Beemod 4.40 and the 4.40 packages.
The error I received is as follows:

VBSP failed.

[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "vbsp.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module_'type' object is not subscriptable
  File "precomp\template_brush.py", line 320, in <module>
[10968] Failed to execute script compiler_launch

I had opened a fresh chamber with nothing in it and tried to build it.  P2 instantly said, “There was an error building the puzzle.”  I only have 1 UCP installed and it is Konclans light strip package.

**Comment by TeamSpen210** [comment]
This should be fixed in version 4.40.1, can you grab that?

**Comment by zooz8882** [comment]
> This should be fixed in version 4.40.1, can you grab that?

I just downloaded the newest application and newest packages from #bee-announcements in the discord and it seems to have worked.  The map compiled with nothing in it with no problems!
