### ISSUE TITLE
Compile error from antline corners

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#3900]
Certain configurations of antline corners cause compile errors. I'm not sure exactly what setup causes the error, so I'll just attach the [map](https://github.com/BEEmod/BEE2-items/files/7042539/1629844075.txt) so TeamSpen can take a look at it. Style is Clean.

<details>
<summary>Compile Log</summary>

```
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 435, in __call__
KeyError: 2803088882368

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 603, in check_all
  File "precomp\conditions\__init__.py", line 250, in test
  File "precomp\conditions\__init__.py", line 239, in test_result
  File "precomp\conditions\__init__.py", line 439, in __call__
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\antlines.py", line 424, in res_antlaser
  File "precomp\conditions\antlines.py", line 148, in rem_ant_straight
KeyError: (Vec_tuple(x=1024.0, y=768.0, z=360.0), Vec_tuple(x=-1.0, y=0.0, z=0.0))
```
</details>

**Comment by TeamSpen210** [comment]
Ah, found the issue - when you place the corners with two different orientations to go around a corner, it places two straight segments. But since you placed the corner at the edge, one of those was zero-long which I didn't account for.
