### ISSUE TITLE
Failed to execute script "bee2_launch

### ISSUE THREAD

**Issue by LazyPlaying** [BEEmod/BEE2-items#4117]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 64 bit

### Description of the bug

after opening BEE2.exe it gives an error "failed to execute  BEE2_launch"
![image](https://user-images.githubusercontent.com/94288255/164654285-1fab1680-fe8c-4a61-bd0e-d4e78994192e.png)

### Expected behavior

after opening BEE2.exe, the menu should open

### Steps to reproduce

Step 1. download version and after packages for it
Step 2. extract to another folder
Step 3. open BEE2.exe

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\__init__.py", line 10, in <module>
  File "tkinter\__init__.py", line 2270, in __init__
This probably means that Tcl wasn't installed properly.
```

**Comment by joethegamer100** [comment]
redownload see if that fixes it 
idk man

**Comment by LazyPlaying** [comment]
> redownload see if that fixes it idk man

I did, nothing helped. I downloaded few versions : all for me nonfunctional (same error)

**Comment by LazyPlaying** [comment]
![image](https://user-images.githubusercontent.com/94288255/164651875-9ac526fb-b730-4a3f-9465-873524a0b5b4.png)
lower versions:

**Comment by TeamSpen210** [comment]
Can you post your complete log file?

**Comment by LazyPlaying** [comment]
> Can you post your complete log file?

Sure, here - Traceback (most recent call last):
  File "BEE2_launch.pyw", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\__init__.py", line 10, in <module>
  File "tkinter\__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {D:\Ð¡ÐµÐ¼ÑÐ½\ÐÐ³ÑÑ\BEE2\tcl} D:/Ð¡ÐµÐ¼ÑÐ½/ÐÐ³ÑÑ/BEE2/tcl8.6 D:/CENSORED/Games/lib/tcl8.6 D:/CENSORED/Games/lib/tcl8.6 D:/CENSORED/lib/tcl8.6 D:/CENSORED/Games/library D:/CENSORED/library D:/CENSORED/tcl8.6.9/library D:/tcl8.6.9/library



This probably means that Tcl wasn't installed properly.

**Comment by LazyPlaying** [comment]
AHAHAHAHAHA!!! SO FUNNY. I CHANGED BEE2 LOCATION AND EVERYTHING OK, LOOOLLLLOOLOLOL

**Comment by LazyPlaying** [comment]
Everything was fine, but at one moment the BEE2 directory became unsupported
