### ISSUE TITLE
Funnel inputs cause a compile error on Python 3.11

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2-items#4259]
```
Traceback (most recent call last):
  File "compiler_launch.py", line 19, in <module>
  File "trio\_core\_run.py", line 2010, in run
  File "vbsp.py", line 1638, in main
  File "precomp\connections.py", line 630, in calc_connections
ValueError: Excursion Funnel "tb11732" has inputs, but no valid types!
```

**Comment by TeamSpen210** [comment]
What style are you using? This works fine for me in Clean. Actually, this might be a 3.11 issue, enums changed subtly.
