### ISSUE TITLE
Map not building

### ISSUE THREAD

**Issue by Legeend28** [BEEmod/BEE2-items#4262]
### BEE2 Application Version

V4.42.0

### BEE2 Package Version

V4.42.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
VBSP failed.

trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2.4.42.0 64-bit VBSP hook initiallised, srctools v2.3.4.
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.collisions"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] brushLoc.read_from_map(): Analysed map, filling air... (264 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] corridor.analyse_and_modify(): Forcing elevator spawn!
[I] corridor.analyse_and_modify(): sp_exit_horizontal corridor selected 3 -> Corridor(instance='instances/BEE2/clean/elevator_sp/door_exit_4.vmf', fixups={'$horiz_cam': '1', '$frame': 'door', '$exit_folder': 'instances/BEE2/clean/elevator_sp/exit_'}, orig_index=4, legacy=False)
[I] corridor.analyse_and_modify(): sp_entry_horizontal corridor selected 5 -> Corridor(instance='instances/BEE2/clean/elevator_sp/door_entrance_6.vmf', fixups={'$horiz_cam': '1', '$frame': 'door'}, orig_index=6, legacy=False)
[I] corridor.analyse_and_modify(): Game Mode: {<GameMode.SP: 'sp'>}
[I] corridor.analyse_and_modify(): Player Start: {False}
[I] corridor.analyse_and_modify(): Map global info: Info(is_publishing=False, start_at_elevator=True, game_mode=<GameMode.SP: 'sp'>, _attrs=defaultdict(<class 'bool'>, {'goo': True}), corr_entry=Corridor(instance='instances/BEE2/clean/elevator_sp/door_entrance_6.vmf', fixups={'$horiz_cam': '1', '$frame': 'door'}, orig_index=6, legacy=False), corr_exit=Corridor(instance='instances/BEE2/clean/elevator_sp/door_exit_4.vmf', fixups={'$horiz_cam': '1', '$frame': 'door', '$exit_folder': 'instances/BEE2/clean/elevator_sp/exit_'}, orig_index=4, legacy=False))
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (5 antlines)
[I] vbsp.change_ents(): Editing Other Entities...
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] (<VALVE_GEOMETRY>/items/track_plat) collisions.res_mod_conditions(): "raillift30":instances/BEE2/clean/items/track/platform_oscillate.vmf -> coll []
[I] (<VALVE_GEOMETRY>/items/track_plat) collisions.res_mod_conditions(): "raillift20":instances/BEE2/clean/items/track/platform_oscillate.vmf -> coll []
[I] (<VALVE_GEOMETRY>/items/track_plat) collisions.res_mod_conditions(): "raillift25":instances/BEE2/clean/items/track/platform_oscillate.vmf -> coll []
[I] (<BEE2_CATWALK>/items/clean) cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Generating item IO...
[E] (MetaCondition "gen_item_outputs") cond.core.check_all(): Error in MetaCondition "gen_item_outputs":
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 695, in check_all
  File "precomp\conditions\__init__.py", line 275, in test
  File "precomp\conditions\__init__.py", line 257, in test_result
  File "precomp\conditions\__init__.py", line 525, in __call__
  File "<string>", line 1, in <lambda>
  File "precomp\connections.py", line 811, in gen_item_outputs
  File "precomp\connections.py", line 1032, in add_item_inputs
  File "precomp\conditions\__init__.py", line 1082, in resolve_value
  File "srctools\vmf.py", line 2839, in substitute
  File "srctools\vmf.py", line 2825, in replacer
KeyError: "$start_active not found, known: ['$is_glass', '$connectioncount']"
```

### Additional information

clean style
(all options in image)
![Screenshot 2022-12-11 223205](https://user-images.githubusercontent.com/91764792/206954812-97650d5b-e37b-4e8e-96d8-e5955f959671.png)

**Comment by TeamSpen210** [comment]
This is an issue with non-oscillating track platforms, you can try toggling that on/off potentially.
