### ISSUE TITLE
50´s Old Aperture: Corridor N°3 causes "Failure To Compile".

### ISSUE THREAD

**Issue by PatooTheWheatleyFan** [BEEmod/BEE2-items#4263]
### BEE2 Application Version

4.42.0

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
Can anyone help me? I am trying to build a map inspired by Portal Epic Edition, but there is always a compile error, no matter what I do. Here it is:
VBSP failed.

trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2.4.42.0 64-bit VBSP hook initiallised, srctools v2.3.4.
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.collisions"!
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): normal.black.wall: Unknown texture names 1x2
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'music_location_sp': '-2824 2040 -768', 'voice_pack': 'BEE2_WHEATLEY'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] brushLoc.read_from_map(): Analysed map, filling air... (306 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] corridor.analyse_and_modify(): sp_entry_horizontal corridor selected 2 -> Corridor(instance='instances/BEE2/50s/sphere_sp/entrance_corridor_3.vmf', fixups={'$template': 'BEE2_50s_CORRIDOR_3', '$door': 'testchamber'}, orig_index=3, legacy=False)
[I] corridor.analyse_and_modify(): sp_exit_horizontal corridor selected 1 -> Corridor(instance='instances/BEE2/50s/sphere_sp/exit_corridor_2.vmf', fixups={'$door': 'testchamber', '$fizz_folder': 'instances/bee2/50s/sphere_sp/exit_corr_lobby/fizz_'}, orig_index=2, legacy=False)
[I] corridor.analyse_and_modify(): Game Mode: {<GameMode.SP: 'sp'>}
[I] corridor.analyse_and_modify(): Player Start: {False}
[I] corridor.analyse_and_modify(): Map global info: Info(is_publishing=False, start_at_elevator=False, game_mode=<GameMode.SP: 'sp'>, _attrs=defaultdict(<class 'bool'>, {}), corr_entry=Corridor(instance='instances/BEE2/50s/sphere_sp/entrance_corridor_3.vmf', fixups={'$template': 'BEE2_50s_CORRIDOR_3', '$door': 'testchamber'}, orig_index=3, legacy=False), corr_exit=Corridor(instance='instances/BEE2/50s/sphere_sp/exit_corridor_2.vmf', fixups={'$door': 'testchamber', '$fizz_folder': 'instances/bee2/50s/sphere_sp/exit_corr_lobby/fizz_'}, orig_index=2, legacy=False))
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (1 antlines)
[I] vbsp.change_ents(): Editing Other Entities...
[W] packing.pack_list(): Packlist "PACK_PLAYER_CLIP_GLASS" does not exist!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 37 Clumps for 563 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] (<BEE2_CATWALK>/items/retro) cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Generating item IO...
[I] (MetaCondition "gen_item_outputs") antlines.export(): Collapsed 2 antline corners
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Item IO generated.
[W] (<BEEMOD_1>/items/door_retro) cond.instances.flag_instvar(): Comparison "start_reversed 1" has no $var, assuming first value. Please use $ when referencing vars.
[W] instanceLocs.get_subitems(): Invalid custom instance name - "single" for <item_rail_platform> (Valid: {'static': 'instances/bee2/50s/items/track/static.vmf'})
[E] (<BEE2_OLD_AP>/items/mandatory/50s/entry_door) cond.core.check_all(): Error in <BEE2_OLD_AP>/items/mandatory/50s/entry_door:
Traceback (most recent call last):
  File "precomp\template_brush.py", line 324, in visgrouped
KeyError: 'danger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 695, in check_all
  File "precomp\conditions\__init__.py", line 275, in test
  File "precomp\conditions\__init__.py", line 257, in test_result
  File "precomp\conditions\__init__.py", line 539, in __call__
  File "precomp\conditions\brushes.py", line 649, in place_template
  File "precomp\template_brush.py", line 717, in import_template
  File "precomp\template_brush.py", line 326, in visgrouped
ValueError: Unknown visgroup "danger" for "BEE2_50S_CORRIDOR_3"! (valid: '', 'gel_dropper', 'gel_bounce', 'airpockets', 'safetyfirst', 'gel_speed', 'platform', 'spallation', 'pgun')
```

### Additional information
![Captura de pantalla (22)](https://user-images.githubusercontent.com/120414266/207140531-70736973-3ed2-4fef-9d86-8ca694f8d279.png)

**Comment by PatooTheWheatleyFan** [comment]
Also I forgot to metion this also appeared to me **********************************************************************************
*** ERROR: logic_relay InstanceAuto1-global_ents-environment_testchamber has been triggered but is awaiting refire. OUTPUTS WILL NOT BE FIRED!!!
*

**Comment by LautaroL20** [comment]
According to your log error, it seems that there is a problem with corridor number 3 from 50s Old Aperture: `ValueError: Unknown visgroup "danger" for "BEE2_50S_CORRIDOR_3"!` can you please choose another corridor for your map and then try building it? Let me know if it compiles or not.

**Comment by PatooTheWheatleyFan** [comment]
It worked! I used corridor 4 from old aperture. And restarted my computer. And it worked!

**Comment by LautaroL20** [comment]
This must stay open as the issue still was not fixed in the BEEmod builds.
