### ISSUE TITLE
Puzzlemaker failed with "ModuleNotFoundError: No module named "atomicwrites"" (Linux) [VRAD failes]

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2-items#4314]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
#vrad.log
[INFO] vrad.main(): BEE2.4.43.0.dev+f2e4a629 64-bit VRAD hook initiallised, srctools v2.3.10, Hammer Addons v(unknown)
[INFO] vrad.main(): Map path is /home/denisredman/.local/share/Steam/steamapps/common/Portal 2/sdk_content/maps/preview.bsp
[INFO] vrad.main(): Loading Settings...
[INFO] vrad.main(): Reading BSP
[DEBUG] bsp.__get__(): Load game lump BSP_LUMPS.ENTITIES (117860 bytes)
[INFO] vrad.main(): Map status: is_peti=True, is_preview=True light_args=FAST
[INFO] vrad.main(): Done!
[DEBUG] vrad.main(): Filesystems:
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/bee2', constrain_path=True)
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/update/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc3/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc2/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc1/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2/../../Portal 2/portal2/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2/../../Portal 2/portal2_dlc2/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2/../../Portal 2/portal2_dlc1/pak01_dir.vpk')
[DEBUG] vrad.main(): - : VPKFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2/../../Portal 2/update/pak01_dir.vpk')
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/update', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc3', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc2', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc1', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc2', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/portal2_dlc1', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/update', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/platform', constrain_path=True)
[DEBUG] vrad.main(): - : RawFileSystem('/home/denisredman/.local/share/Steam/steamapps/common/Portal 2/platform', constrain_path=True)
[DEBUG] vrad.main(): - : ZipFileSystem('<BSP pakfile>')
[INFO] vrad.main(): Reading our FGD files...
[INFO] vrad.main(): Reading soundscripts...
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_ui.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_player.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_physics.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/level_sounds_aperture.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_portal.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_weapons_portal.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_energy_ball.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_props_aperture.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_vo.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_animation.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_auto_generated.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_turret_auto_generated.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_cave_auto_generated.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_sphere03_auto_generated.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_world.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_announcer_auto_generated.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_cores_auto_generated.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/level_sounds_music_portal.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/level_sounds_escape.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_aperture_ai.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_energy_ball.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_turret_portal.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_rocket_turret.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_glados_cores.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_ballbot.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_eggbot.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_combine_ball.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_combine_ball_episodic.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_hover_turret.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/npc_sounds_turret.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_npc.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_player_portal2.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_nugget.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/level_sounds_tempcontent.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_weapons_paintgun.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_paint_player.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_paint.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_scripted_sequence.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_vfx.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_music.txt from cache
[WARNING] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A1.txt" does not exist!
[WARNING] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A2.txt" does not exist!
[WARNING] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A3.txt" does not exist!
[WARNING] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A4.txt" does not exist!
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_music_mp.txt from cache
[WARNING] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_BR_world.txt" does not exist!
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_taunts_egg.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_taunts_ball.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_dlc1_glados.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_dlc1_world.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_music_dlc2.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_dlc2_cave.txt from cache
[DEBUG] packlist.add_cached_file(): Loading scripts/game_sounds_editor.txt from cache
[INFO] vrad.main(): Reading particles....
[DEBUG] packlist.add_cached_file(): Loading particles/debug.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/fire_01.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/error.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/burning_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/weapon_fx_hl2.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/water_impact.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/tracer_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/rain_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/impact_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/blood_impact.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/portal_projectile.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/portalgun.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/cleansers.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/fire_01_portal.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/tubes.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/environment.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/portals.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/portal2_coop_ping_effect.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/laser_relay_effects.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/projected_wall.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/dust_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/drip_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/tractor_beam_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/robot_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/spark_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/exploding_futbol.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/portalgun.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/confetti.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/environmental_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/paint_fizzler.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/paint_splats_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/player_paint_effects.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/paint_bomb_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/flashlight_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/scene_fx.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/laser_relay_2.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/br_train_effects.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/bee2_p1_elev_beam.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/paint_splats_fx_reflect.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/paint_bomb_fx_reflect.pcf from cache
[DEBUG] packlist.add_cached_file(): Loading particles/bee2_pgun_pedestal.pcf from cache
[INFO] vrad.main(): Loading transforms...
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 26, in <module>
  File "trio/_core/_run.py", line 2010, in run
  File "vrad.py", line 239, in main
  File "vrad.py", line 48, in load_transforms
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "transforms_stub.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "/home/denisredman/git/BEE2.4/hammeraddons/transforms/geocable.py", line 24, in <module>
    from hammeraddons.mdl_compiler import ModelCompiler
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "hammeraddons/mdl_compiler.py", line 23, in <module>
ModuleNotFoundError: No module named 'atomicwrites'
```

### Additional information

Package called python-atomicwrites is installed.
"atomicwrites" version: `1.4.1-2`
Images:
![anothererror](https://user-images.githubusercontent.com/88984260/233694632-b689c966-1483-4eab-9327-00c48cb692cd.png)
![anothererrormore](https://user-images.githubusercontent.com/88984260/233694649-39a25f9f-c9df-4aef-8aa3-002844fd9f25.png)

**Comment by Denisredmans** [comment]
I decided to try a very crutch way.
But perhaps a new error during compilation occurs because of this "fix".
