### ISSUE TITLE
ive got a error

### ISSUE THREAD

**Issue by qillla** [BEEmod/BEE2-items#4365]
### BEE2 Application Version

latest one 

### BEE2 Package Version

also the latest one

### Logs and Reports

```shell
Traceback (most recent call last):
  File "trio\_core\_run.py", line 850, in __aexit__
  File "app\UI.py", line 757, in export_editoritems
  File "app\gameMan.py", line 707, in export
  File "os.py", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'c:\\program files\\portal 2\\bin\\bee2\\'
```

**Comment by qillla** [comment]
also the os is windows 11

**Comment by qillla** [comment]
also because of that the items dont appear also

**Comment by TeamSpen210** [comment]
You might need to change the security settings on the Portal 2 folder. Because it's in program files, windows puts security settings that prevent non-installer programs from modifying it.
