### ISSUE TITLE
BEE2.4 ARCTIFACT BUILD: Compiling an empty chamber in any style will cause: "Failure To Compile".

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4388]
### BEE2 Application Version

beemod2_9f73df920a54ca83601059be1be88357ddbba638_win32

### BEE2 Package Version

beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2.4.41.0 32-bit VBSP hook initiallised, srctools v2.2.3.
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/', 'error_translations': 'D:\\Steam\\Steamapps\\common\\BEEMOD BUILD\\i18n\\es.mo'}
[E] vbsp.load_settings(): Failed to parse editoritems dump. Re-export BEE2.
Traceback (most recent call last):
  File "vbsp.py", line 128, in load_settings
  File "editoritems.py", line 1804, in __setstate__
ValueError: too many values to unpack (expected 29)
```

**Comment by TeamSpen210** [comment]
Looks like you have an old copy of the compiler, did it export? Perhaps it's not finding the compiler when frozen.

**Comment by LautaroL20** [comment]
At the time of exporting, it is supposed to have did a full export. Maybe it's happening the old bug of not overwritting old resources again?

**Comment by LautaroL20** [comment]
Perhaps I should click on `File > Uninstall From Selected Game` and then try to export again?

**Comment by TeamSpen210** [comment]
It's to do with being frozen, fixed.
