### ISSUE TITLE
BEE2.4 ARTIFACT BUILD: Compiling an empty chamber still causes: "Failure To Compile" - ¿Caused by the outdated artifact package?

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2-items#4391]
### BEE2 Application Version

beemod2_6095b208c79342ae7ad43f2fbc4353ab1f2b4318_win32

### BEE2 Package Version

beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
VBSP failed.

[I] vbsp.main(): BEE2.4.43.0.dev+6095b208 32-bit VBSP hook initiallised, srctools v2.3.15.
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 23, in <module>
  File "trio\_core\_run.py", line 2251, in run
  File "vbsp.py", line 1516, in main
  File "precomp\conditions\__init__.py", line 828, in import_conditions
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 99, in _pyi_pkgutil_iter_modules
  File "PyInstaller\loader\pyimod02_importers.py", line 132, in toc_tree
  File "PyInstaller\loader\pyimod02_importers.py", line 149, in _build_pyz_prefix_tree
TypeError: 'str' object does not support item assignment
[3755264] Failed to execute script 'compiler_launch' due to unhandled exception!
Traceback (most recent call last):
  File "compiler_launch.py", line 23, in <module>
  File "trio\_core\_run.py", line 2251, in run
  File "vbsp.py", line 1516, in main
  File "precomp\conditions\__init__.py", line 828, in import_conditions
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 99, in _pyi_pkgutil_iter_modules
  File "PyInstaller\loader\pyimod02_importers.py", line 132, in toc_tree
  File "PyInstaller\loader\pyimod02_importers.py", line 149, in _build_pyz_prefix_tree
TypeError: 'str' object does not support item assignment
```

### Additional information

Maybe this compiling problem is caused due to the outdated arctifact package?

**Comment by LautaroL20** [comment]
I just realised that it´s called "Artifact" and not "Arctifact", whops.

**Comment by TeamSpen210** [comment]
I think I might have fixed this + the other issues with [build 67](https://github.com/BEEmod/BEE2.4/actions/runs/7013874718), could you confirm?

**Comment by LautaroL20** [comment]
Unfortunately, none of the issues were fixed. I can not build any chambers because each time I try to export a BEEmod palette to the game, it happens this: https://github.com/BEEmod/BEE2.4/issues/2000

**Comment by LautaroL20** [comment]
This may be unlikely, but is there a possibility that the latest artifact downloads are not including the updated files for some reason?

**Comment by vrad-exe** [comment]
Does this still happen?

**Comment by vrad-exe** [comment]
Closing
