### ISSUE TITLE
Piston Platform causes an error when compiling.

### ISSUE THREAD

**Issue by CardsAndGamesYT** [BEEmod/BEE2-items#4404]
### BEE2 Application Version

4.44.1

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Having a the Piston Platform item anywhere in the map will cause the chamber to not compile.

### Expected behavior

It should not have caused a compile error.

### Steps to reproduce

Place the Piston Platform item anywhere in the map.

### Logs and Reports

```shell
[W] (<VALVE_TEST_ELEM>/items/cube) cond.positioning.check_brush_at_loc(): Using type=same in posIsSolid is deprecated, put this in mode!
[E] (<VALVE_GEOMETRY>/items/piston_plat) cond.core.check_all(): Error in <VALVE_GEOMETRY>/items/piston_plat:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 716, in check_all
  File "precomp\conditions\__init__.py", line 279, in test
  File "precomp\conditions\__init__.py", line 261, in test_result
  File "precomp\conditions\__init__.py", line 549, in __call__
  File "precomp\conditions\__init__.py", line 1313, in test_cond
  File "precomp\conditions\__init__.py", line 279, in test
  File "precomp\conditions\__init__.py", line 255, in test_result
ValueError: "Collisions" is not a valid condition result!
```

### Additional information

I'm using the Original Clean style
I've tested it with and without connections, with and without `Auto-drop first cube` ticked, and I've tested it in an outside of goo. same result every time.

**Comment by CardsAndGamesYT** [comment]
Does this fix it for everything? I just got the same error from the light strip
```
[W] (<VALVE_GEOMETRY>/items/light_strip) cond.core.res_switch(): Switch uses deprecated field "flag", this has been renamed to "test".
[E] (<VALVE_GEOMETRY>/items/light_strip) cond.core.check_all(): Error in <VALVE_GEOMETRY>/items/light_strip:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 716, in check_all
  File "precomp\conditions\__init__.py", line 279, in test
  File "precomp\conditions\__init__.py", line 261, in test_result
  File "precomp\conditions\__init__.py", line 549, in __call__
  File "precomp\conditions\__init__.py", line 1400, in apply_switch
  File "precomp\conditions\__init__.py", line 255, in test_result
ValueError: "Collisions" is not a valid condition result!
```

**Comment by CardsAndGamesYT** [comment]
Specifically on Cube Type 5
