### ISSUE TITLE
There was an error building the puzzle.

### ISSUE THREAD

**Issue by DexperienceIsTrashAtCSS** [BEEmod/BEE2-items#4429]
### BEE2 Application Version

v2.4.45.2 64-bit

### BEE2 Package Version

v4.45.0

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['D:/SteamLibrary/steamapps/common/Portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'D:/SteamLibrary/steamapps/common/Portal 2/portal2/', 'D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 56, in <module>
  File "trio\_core\_run.py", line 2303, in run
  File "vbsp.py", line 1608, in main
  File "srctools\game.py", line 33, in __init__
  File "srctools\keyvalues.py", line 519, in parse
srctools.keyvalues.KeyValError: End of text reached with remaining open sections.

File ended with at least one keyvalue that didn't have an ending "}".
Open properties: 
- Root at line 1
- "GameInfo" on line 2
Error occurred with file "D:\SteamLibrary\steamapps\common\Portal 2\portal2\gameinfo.txt".
[33852] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

Portal 1 Style

**Comment by TeamSpen210** [comment]
Can you post your `D:\SteamLibrary\steamapps\common\Portal 2\portal2\gameinfo.txt` file?

**Comment by DexperienceIsTrashAtCSS** [comment]
eInfo"
{
	game 		"PORTAL 2"
	title 		"PORTAL 2"
	GameData	"portal2.fgd"
	gamelogo 	1

	SupportsDX8     0
	SupportsXbox360 1

	FileSystem
	{
		SteamAppId				620		// This will mount all the GCFs we need (240=CS:S, 220=HL2).
		ToolsAppId				211		// Tools will load this (ie: source SDK caches) to get things like materials\debug, materials\editor, etc.
		
		//
		// The code that loads this file automatically does a few things here:
		//
		// 1. For each "Game" search path, it adds a "GameBin" path, in <dir>\bin
		// 2. For each "Game" search path, it adds another "Game" path in front of it with _<langage> at the end.
		//    For example: c:\hl2\cstrike on a french machine would get a c:\hl2\cstrike_french path added to it.
		// 3. For the first "Game" search path, it adds a search path called "MOD".
		// 4. For the first "Game" search path, it adds a search path called "DEFAULT_WRITE_PATH".
		//

		//
		// Search paths are relative to the base directory, which is where hl2.exe is found.
		//
		// |gameinfo_path| points at the directory where gameinfo.txt is.
		// We always want to mount that directory relative to gameinfo.txt, so
		// people can mount stuff in c:\mymod, and the main game resources are in
		// someplace like c:\program files\valve\steam\steamapps\half-life 2.
		//

		SearchPaths
		{
			Game				|gameinfo_path|.
			Game	|gameinfo_path|../bee2
			Game	"BEE2"
	}
}

**Comment by TeamSpen210** [comment]
Get rid of the `Game "BEE2"` line, and replace it with a `}`. That's missing for some reason, maybe BEE malfunctioned in the past.

**Comment by TeamSpen210** [comment]
That's actually version `BEE2.4.43.0` for VRAD, you might need to export again to make sure you have new compilers..
