### ISSUE TITLE
"Failed to execute script 'compiler_launch' due to unhandled exception!'

### ISSUE THREAD

**Issue by SlimySqueed** [BEEmod/BEE2-items#4434]
### BEE2 Application Version

4.45.2 64bit

### BEE2 Package Version

4.45.0 (Packages) / 4.44.0 (Music packages)

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['E:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'E:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'E:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "E:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "E:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[14576] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

Every time I try to build a puzzle, even if I don't change or add anything to it, I quickly get "There was an error building the puzzle" right before the "Building Geometry" progress bar finishes. Also, the geometry seems to almost instantly finish (before the error message appearing) compared to before where the geometry would take at least 10 seconds before it would finish.

![PeTI_image](https://github.com/BEEmod/BEE2-items/assets/130199943/58121ff5-1c49-47cf-abe8-d120a838b08d)
![PeTI_BuildError](https://github.com/BEEmod/BEE2-items/assets/130199943/85655edc-d6a8-40eb-9c04-bf8ab41caff4)

I've tried to clear my game cache, verify game files, checking and editing my gameinfo.txt, and some other methods I've found online. I did find that when I verify my game files after exporting from BEE2.4, 6 files failed to validate. After validating the files, I can successfully build the puzzle, but now all the BEE2.4 exported files and custom elements are gone.

**Comment by TeamSpen210** [comment]
See Beemod/BEE2.4#2054, you have to pick a voice pack right now.
