### ISSUE TITLE
"There was an error building the puzzle"

### ISSUE THREAD

**Issue by go60wm** [BEEmod/BEE2-items#4440]
### BEE2 Application Version

BEE2 v4.45.2 win 64

### BEE2 Package Version

BEE2 v4.45.0 Packages

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['c:/program files (x86)/steam/steamapps/common/portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'c:/program files (x86)/steam/steamapps/common/portal 2/portal2/', 'c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'remove_info_lighting': '1', 'remove_pedestal_plat': '1'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse(): Floorbeam: FloorbeamConf(distance=range(32, 128, 8), brush=Solid(map=<srctools.vmf.VMF object at 0x000001B64BBEAB40>, id=52, sides=[<srctools.vmf.Side object at 0x000001B64C192480>, <srctools.vmf.Side object at 0x000001B64C192520>, <srctools.vmf.Side object at 0x000001B64C192700>, <srctools.vmf.Side object at 0x000001B64C1927A0>], visgroup_ids=set(), hidden=False, group_id=None, vis_shown=True, vis_auto_shown=True, cordon_solid=None, editor_color=Vec(0, 121, 198)), width=2.0, border=4)
[I] barriers.parse_conf(): Parsed 3 barrier types, 1 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[15944] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

I really wanted to use this again, but am having this error. im using the portal 1 style and thats it. This even happens with nothing placed.

**Comment by TeamSpen210** [comment]
See BEEmod/BEE2.4#2054, you have to select some voicelines right now.
