### ISSUE TITLE
Error building puzzle

### ISSUE THREAD

**Issue by CubeSeer** [BEEmod/BEE2-items#4445]
### BEE2 Application Version

4.45.2 64bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['G:/SteamLibrary/steamapps/common/Portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'G:/SteamLibrary/steamapps/common/Portal 2/portal2/', 'G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "G:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[5324] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

Clean style, no announcers (multiverse Cave disabled)

**Comment by O-39889** [comment]
can confirm, also having this issue

**Comment by TeamSpen210** [comment]
This is the same as #4436, you need to choose a voice line right now.

**Comment by CubeSeer** [comment]
that's bullshit, why even allow the option to mute announcers when the game functions without them? atleast make empty/silent sound files.

**Comment by CubeSeer** [comment]
the bug isn't "fixed", the game can't compile without announcers so the issue will remain open until the bug is resolved.

**Comment by O-39889** [comment]
I don't think it's marked as "fixed"? Like, even in that issue that TeamSpen was linking to.
> that's bullshit, why even allow the option to mute announcers when the game can't function without them? atleast make empty/silent sound files.
From what I understand, it was working properly until the devs did some refactoring but forgot to account for this case.
For now you can just pick a set of voicelines but disable all of them (gear icon to the left of the selected option). I'd recommend picking Caroline or some other one that doesn't have a lot of them bc there is no option to deselect multiple at once so I had to scroll through every GLaDOS voiceline manually…
Oh, and also, probably also chill out a bit please, this is a more serious environment after all, even though it's just a tool for a video game
