### ISSUE TITLE
Compile error if item config contains quotes

### ISSUE THREAD

**Issue by HyperAnimates** [BEEmod/BEE2-items#4454]
### BEE2 Application Version

4.45.2 64bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['c:/program files (x86)/steam/steamapps/common/portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'c:/program files (x86)/steam/steamapps/common/portal 2/portal2/', 'c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[E] vbsp.load_settings(): Failed to parse required config file. Re-export BEE2.
  + Exception Group Traceback (most recent call last):
  |   File "vbsp.py", line 110, in load_settings
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "srctools\dmx.py", line 1571, in _parse_kv2_element
    |   File "enum.py", line 744, in __call__
    |   File "enum.py", line 1158, in __new__
    | ValueError: 'conf_v1' is not a valid ValueType
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "srctools\dmx.py", line 1571, in _parse_kv2_element
    |   File "enum.py", line 744, in __call__
    |   File "enum.py", line 1158, in __new__
    | ValueError: 'subconf' is not a valid ValueType
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "srctools\dmx.py", line 1571, in _parse_kv2_element
    |   File "enum.py", line 744, in __call__
    |   File "enum.py", line 1158, in __new__
    | ValueError: 'text' is not a valid ValueType
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "utils.py", line 648, in task
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "vbsp.py", line 103, in load_dmx_config
    |   File "srctools\dmx.py", line 1330, in parse
    |   File "srctools\dmx.py", line 1509, in parse_kv2
    |   File "srctools\dmx.py", line 1576, in _parse_kv2_element
    |   File "srctools\dmx.py", line 1576, in _parse_kv2_element
    |   File "srctools\dmx.py", line 1576, in _parse_kv2_element
    |   File "srctools\dmx.py", line 1539, in _parse_kv2_element
    |   File "src\\srctools\\_tokenizer.pyx", line 1034, in srctools._tokenizer.BlockIter.__next__
    | srctools.tokenizer.TokenSyntaxError: Expected BRACE_OPEN, but got Token.STRING!
    | Error occurred on line 121, with file "bee2/config.dmx".
    +------------------------------------
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | BaseExceptionGroup: Exceptions from Trio nursery (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +---------------- 2 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "vbsp.py", line 110, in load_settings
    |   File "trio\_core\_run.py", line 963, in __aexit__
    | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "srctools\dmx.py", line 1571, in _parse_kv2_element
      |   File "enum.py", line 744, in __call__
      |   File "enum.py", line 1158, in __new__
      | ValueError: 'conf_v1' is not a valid ValueType
      | 
      | During handling of the above exception, another exception occurred:
      | 
      | Traceback (most recent call last):
      |   File "srctools\dmx.py", line 1571, in _parse_kv2_element
      |   File "enum.py", line 744, in __call__
      |   File "enum.py", line 1158, in __new__
      | ValueError: 'subconf' is not a valid ValueType
      | 
      | During handling of the above exception, another exception occurred:
      | 
      | Traceback (most recent call last):
      |   File "srctools\dmx.py", line 1571, in _parse_kv2_element
      |   File "enum.py", line 744, in __call__
      |   File "enum.py", line 1158, in __new__
      | ValueError: 'text' is not a valid ValueType
      | 
      | During handling of the above exception, another exception occurred:
      | 
      | Traceback (most recent call last):
      |   File "utils.py", line 662, in _task
      |   File "utils.py", line 648, in task
      |   File "trio\_threads.py", line 471, in to_thread_run_sync
      |   File "outcome\_impl.py", line 213, in unwrap
      |   File "trio\_threads.py", line 397, in do_release_then_return_result
      |   File "outcome\_impl.py", line 213, in unwrap
      |   File "trio\_threads.py", line 416, in worker_fn
      |   File "vbsp.py", line 103, in load_dmx_config
      |   File "srctools\dmx.py", line 1330, in parse
      |   File "srctools\dmx.py", line 1509, in parse_kv2
      |   File "srctools\dmx.py", line 1576, in _parse_kv2_element
      |   File "srctools\dmx.py", line 1576, in _parse_kv2_element
      |   File "srctools\dmx.py", line 1576, in _parse_kv2_element
      |   File "srctools\dmx.py", line 1539, in _parse_kv2_element
      |   File "src\\srctools\\_tokenizer.pyx", line 1034, in srctools._tokenizer.BlockIter.__next__
      | srctools.tokenizer.TokenSyntaxError: Expected BRACE_OPEN, but got Token.STRING!
      | Error occurred on line 121, with file "bee2/config.dmx".
      +------------------------------------
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "vbsp.py", line 125, in load_settings
    | SystemExit: 1
[11336] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

This happens with a blank test chamber with nothing in it. Here are some photos of my items, export and compile options including a photo of the error. I don't have any ucp's installed. I just downloaded BEE2 and this kept happening.
![Beemod](https://github.com/user-attachments/assets/b91863d5-6943-40dd-b0a6-2b2163ab6ba6)
![Screenshot (284)](https://github.com/user-attachments/assets/bcb49a94-b5ac-4764-bbc3-3da6529e641c)

**Comment by HyperAnimates** [comment]
I forgot to mention that I uninstalled bee mod and verified the integrity of the game's files. Then, I re-installed bee mod but still got this error. I even cleared multiple caches but it still didn't work.

**Comment by TeamSpen210** [comment]
Can you attach a copy of `Portal 2/bin/bee2/config.dmx`? Also right now a voice line pack needs to be selected.

**Comment by HyperAnimates** [comment]
Here is a link to media fire where you can download it. It wouldn't allow me to put the file in here directly.
https://www.mediafire.com/file/rag84279giyy7ls/config.dmx/file

**Comment by HyperAnimates** [comment]
> Can you attach a copy of `Portal 2/bin/bee2/config.dmx`? Also right now a voice line pack needs to be selected.

I selected a voice line but it still doesn't work

**Comment by TeamSpen210** [comment]
The DMX file's problem is the `"Insert text here"` value set in Saismee's text popup item, best way would be to re-add that so you can remove it.

**Comment by HyperAnimates** [comment]
Ok will do!

**Comment by TeamSpen210** [comment]
This is now escaped correctly.
