### ISSUE TITLE
[Linux, NixOS] BEEmod fails to compile chamber: ImportError: cannot import name 'areaportals' from partially initialized module 'postcomp.transforms'

### ISSUE THREAD

**Issue by L1Z3** [BEEmod/BEE2-items#4458]
### BEE2 Application Version

Tested on 4.44.0, 4.45.2

### BEE2 Package Version

Tested on 4.44.0, 4.45.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
VRAD failed.

Need implementation of utils.check_shift()!
[I] vrad.main(): BEE2.4.44.0 64-bit VRAD hook initiallised, srctools v2.4.1, Hammer Addons v(unknown)
[I] vrad.main(): Map path is /home/liz/.local/share/Steam/steamapps/common/Portal 2/sdk_content/maps/preview.bsp
[I] vrad.main(): Loading Settings...
[I] vrad.main(): Reading BSP
[I] vrad.main(): Map status: is_peti=True, is_preview=True light_args=FAST
[I] vrad.main(): Done!
[I] vrad.main(): Reading soundscripts...
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A1.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A2.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A3.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_music_A4.txt" does not exist!
[W] packlist.load_soundscript_manifest(): Soundscript "scripts/game_sounds_BR_world.txt" does not exist!
[I] vrad.main(): Reading particles....
[I] vrad.main(): Loading transforms...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 37, in <module>
  File "trio/_core/_run.py", line 2407, in run
  File "vrad.py", line 238, in main
  File "vrad.py", line 45, in load_transforms
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "transforms_stub.py", line 2, in <module>
ImportError: cannot import name 'areaportals' from partially initialized module 'postcomp.transforms' (most likely due to a circular import) (/home/liz/.local/share/Steam/steamapps/common/Portal 2/bin/linux32/bee2_bin/postcomp/transforms.pyc)
[PYI-1938621:ERROR] Failed to execute script 'compiler_launch' due to unhandled exception!
```

### Additional information

I'm attempting to get BEEmod working on NixOS. With some difficulty, I was able to compile and run the BEEmod app, but when attempting to build any puzzle with BEEmod installed, I get the above error.

**Comment by TeamSpen210** [comment]
This suggests something's wrong with the freezing of the compiler. Did you clone the `HammerAddons` submodule?

**Comment by L1Z3** [comment]
Thanks for the reply! I did clone the repo with `--recurse-submodules`, and i also tried updating the submodules with `git submodule update --init`, as specified in the compilation instructions. 

(I've also had a different issue with the BEEmod executable crashing due to not finding TKinter, but I've fixed that by manually copying in the tk and tcl files into `dist/64bit/BEE2/bin/_tk_data`. It seems like PyInstaller on NixOS has trouble finding the correct TKinter directories.)

If it helps, [here](https://pastebin.com/j6sHEqrx) are the full PyInstaller logs.

**Comment by lewark** [comment]
I'm encountering the same issue on Arch Linux. I'll post an update if I figure anything out.

**Comment by TeamSpen210** [comment]
Venvs should be fine, I always use them. Have you tried a dev build, I've changed a few things around this which might solve the issue.

**Comment by code-apeman** [comment]
Same issue here. I also noticed that there's no `postcomp` directory, not even talking about `transforms.pyc` that... should probably be there?

**Comment by shurikis** [comment]
I'm encountering the same issue on Steam OS. if i delete the folder BEE2.4/hammeraddons/packages before building beemod it works but the cubes don't fall and when i press the button the door doesn't open

**Comment by TeamSpen210** [comment]
Deleting the code that's necessary for it to run isn't going to work. What version are you using?

**Comment by shurikis** [comment]
beemod 2.4.45.2

**Comment by TeamSpen210** [comment]
Try the dev branches then.

**Comment by shurikis** [comment]
In dev branch it says that the map is leaked even in a new map

**Comment by AleXoundOS** [comment]
> I've also had a different issue with the BEEmod executable crashing due to not finding TKinter, but I've fixed that by manually copying in the tk and tcl files into `dist/64bit/BEE2/bin/_tk_data`. It seems like PyInstaller on NixOS has trouble finding the correct TKinter directories.

@L1Z3, please, can you explain exactly what you copied into the `BEE2/bin/_tk_data` folder?

**Comment by AleXoundOS** [comment]
I solved `_tk_data` problem with:
```nix
''
  cp -r ${tk}/lib/tk${lib.versions.major tk.version}.${lib.versions.minor tk.version} $out/dist/64bit/BEE2/bin/_tk_data
''
```

**Comment by AleXoundOS** [comment]
@L1Z3, please, can you share the next steps or a Nix derivation which you wrote?
